name: Run Rest Assured Project

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Code
        uses: actions/checkout@v5

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '25'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.16

      - name: Running Tests
        run: mvn clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: RestAssuredTestResults
          path: "test-output/reports/*.html"